apiVersion: kubescheduler.config.k8s.io/v1
kind: KubeSchedulerConfiguration

leaderElection:
  leaderElect: false

clientConnection:
  kubeconfig: ""

profiles:
  - schedulerName: scheduler-plugins-scheduler
    plugins:
      multiPoint:
        enabled:
          - name: ArchitectureAware
        disabled:
          - name: "*"
    pluginConfig:
      - name: ArchitectureAware
        args:
          orinTag: "r36"
          nanoTag: "latest"
