# Default values for scheduler-plugins-as-a-second-scheduler.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

scheduler:
  name: scheduler-plugins-scheduler
  image: ghcr.io/unict-cclab/kube-scheduler:sophos-v0.1.7
  replicaCount: 1
  leaderElect: false
  nodeSelector:
    kubernetes.io/hostname: k3s-master-01
  affinity: {}
  tolerations: []

controller:
  name: scheduler-plugins-controller
  image: registry.k8s.io/scheduler-plugins/controller:v0.29.7
  replicaCount: 1
  nodeSelector: 
    kubernetes.io/hostname: k3s-master-01
  affinity: {}
  tolerations: []

# LoadVariationRiskBalancing and TargetLoadPacking are not enabled by default
# as they need extra RBAC privileges on metrics.k8s.io.

# plugins:
#   enabled: ["ArchitectureAware","QoSAware","SortingGpuAware"]
#   disabled: ["PrioritySort"] # only in-tree plugins need to be defined here
plugins:
  enabled:
    - ArchitectureAware
    - QoSAware

  disabled: []

  queueSort:
    enabled:
      - SortingGpuAware
    disabled:
      - PrioritySort
# Customize the enabled plugins' config.
# Refer to the "pluginConfig" section of manifests/<plugin>/scheduler-config.yaml.
# For example, for Coscheduling plugin, you want to customize the permit waiting timeout to 10 seconds:
pluginConfig:
  - name: ArchitectureAware
    args:
      mappings:
        - labelValue: "nano"
          tag: "latest"
        - labelValue: "orin"
          tag: "r36"
        - labelValue: "xavier"
          tag: "beta"
  - name: QoSAware
    args:
      mappings:
        - labelValue: "nano"
          factor: 1.0
        - labelValue: "orin"
          factor: 3.0
        - labelValue: "xavier"
          factor: 2.0
  - name: SortingGpuAware
    args: {}   

#pluginConfig:
#- name: Coscheduling
#  args:
#    permitWaitingTimeSeconds: 10 # default is 60
# Or, customize the other plugins
# - name: NodeResourceTopologyMatch
#   args:
#     scoringStrategy:
#       type: MostAllocated # default is LeastAllocated
#- name: SySched
#  args:
#    defaultProfileNamespace: "default"
#    defaultProfileName: "full-seccomp"
