# Default values for scheduler-plugins-as-a-second-scheduler.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

scheduler:
  name: scheduler-plugins-scheduler
  image: ghcr.io/unict-cclab/kube-scheduler:sophos-v0.2.7
  replicaCount: 1
  leaderElect: false
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        preference:
          matchExpressions:
          - key: nodepool
            operator: In
            values:
            - management
  tolerations: []

controller:
  name: scheduler-plugins-controller
  image: registry.k8s.io/scheduler-plugins/controller:v0.29.7
  replicaCount: 1 
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        preference:
          matchExpressions:
          - key: nodepool
            operator: In
            values:
            - management
  tolerations: []

# LoadVariationRiskBalancing and TargetLoadPacking are not enabled by default
# as they need extra RBAC privileges on metrics.k8s.io.

#plugins:
#  enabled: ["LoadAwareResourcesBalancedAllocation"]
#  disabled: ["PrioritySort"] # only in-tree plugins need to be defined here
plugins:
  enabled:
    - loadAwareResourcesBalancedAllocation
    - networkAwareLocalAi
    - architectureAware
  preBind:
    enabled:
      - name: ArchitectureAware
  score:
    enabled:
      - name: NetworkAwareLocalAi
      - name: LoadAwareResourcesBalancedAllocation
  preScore:
    enabled:
      - name: NetworkAwareLocalAi
  # score:
  #   enabled:
  #     - name: QoSAware
  #       weight: 2
#  queueSort:
#    enabled:
#      - SortingGpuAware
#    disabled:
#      - PrioritySort

# Customize the enabled plugins' config.
# Refer to the "pluginConfig" section of manifests/<plugin>/scheduler-config.yaml.
# For example, for Coscheduling plugin, you want to customize the permit waiting timeout to 10 seconds:
pluginConfig:
  - name: ArchitectureAware
    args:
      mappings:
        - labelValue: "nano"
          tag: "latest-nvidia-l4t-arm64"
          backendsPath: "/backends/arm64"
          args:
            - p2p-worker
        - labelValue: "orin"
          tag: "latest-nvidia-l4t-arm64"
          backendsPath: "/backends/arm64"
          args:
            - p2p-worker
        - labelValue: "xavier"
          tag: "beta"
          backendsPath: "/backends/arm64"
          args:
            - p2p-worker
        - labelValue: "amd"
          tag: "latest-aio-cpu"
          backendsPath: "/backends/amd64"
          args:
            - worker
        - labelValue: "amd64"
          tag: "latest-aio-cpu"
          backendsPath: "/backends/amd64"
          args:
            - worker
        - labelValue: "arm64"
          tag: "latest-nvidia-l4t-arm64"
          backendsPath: "/backends/arm64"
          args:
            - p2p-worker
  - name: QoSAware
    args:
      mappings:
        - labelValue: "nano"
          factor: 1.0
        - labelValue: "orin"
          factor: 3.0
        - labelValue: "xavier"
          factor: 2.0
        - labelValue: "amd"
          factor: 1.0
  - name: SortingGpuAware
    args: {}   
#pluginConfig:
#- name: Coscheduling
#  args:
#    permitWaitingTimeSeconds: 10 # default is 60
# Or, customize the other plugins
# - name: NodeResourceTopologyMatch
#   args:
#     scoringStrategy:
#       type: MostAllocated # default is LeastAllocated
#- name: SySched
#  args:
#    defaultProfileNamespace: "default"
#    defaultProfileName: "full-seccomp"
